### ISSUE TITLE
CWD and using project-specific .p4config files

### ISSUE THREAD

**Issue by nall** [mattsawyer77/atom-perforce#24]
My project directory has a .p4config at the root directory which defines P4CLIENT and P4PORT and those values seem to be ignored. Specifically, I get errors when atom-perforce tries to invoke p4 info where it's using the default $P4PORT. This makes me think the CWD must be something other than my project dir and my .p4config isn't being picked up.

Any ideas for working in this type of setup?

**Comment by mattsawyer77** [comment]
Hmm, do you have

```
export P4CONFIG=.p4config
```

in your .bashrc/.zshrc/etc file?

**Comment by nall** [comment]
Yes, I have that export in my .zshrc.

Actually, it looks like it works if I launch atom from the directory 
containing the files (as opposed to launching it via Alfred on OSX). I'm 
fairly new to atom. Is this the expected behavior?

nall.

**Comment by mattsawyer77** [comment]
I think I've found a workaround, and the possible root cause. The workaround is to put your P4\* environment variables in ~/.zshenv (and if that doesn't work, you might as well launch atom from the terminal, which isn't ideal but shouldn't be too painful). If you're on a Mac it might be due to atom/atom#6956.

In the meantime, I'll work on a slightly more brute force method of ascertaining the appropriate vars in the code so the workaround is no longer up to the user.

**Comment by nall** [comment]
Thanks, Matt.

Is your suspicion that I'll need _all_ P4 vars (P4CLIENT, P4PORT) in my 
.zshenv or just the P4CONFIG? If the latter, I can live with that. If 
not I'll need to wait for something else as I have multiple clients 
checked out and a single $P4CLIENT defined won't work.

nall.

**Comment by mattsawyer77** [comment]
In my setup, I leave out P4CLIENT from my .zshenv, and specify that in my .p4config file in the root of the workspace. If that doesn't work for you, let me know.

**Comment by mattsawyer77** [comment]
I've published what should hopefully be a workaround for you (it worked for me when I renamed my .zshenv). Let me know if it doesn't help you @nall.
